import '../styles/globals.scss'
import Navbar from '../components/navbar/navbar'
import Footer from '../components/footer/footer'
import {Fira_Code} from 'next/font/google'

 const inter = Fira_Code({
  weight:['400','500','600','700'],
  style: ['normal'],
  preload: false
 })

 export const metadata={
  title:'Games store',
  description:'Generated by create next app',
 }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><Navbar/>{children}<Footer/></body>
    </html>
  )
}
